### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by southern-boy** [minch-dev/DownTheMoon#13]
### Your DownTheMoon! and Browser Version and Language and Operating System
Waterfox 2022.11 (64-bit)  on Windows 7

How do I make a windows installer for this or how do I install it on Windows?  I did not see that mentioned in the readme.

**Comment by minch-dev** [comment]
You just instal the xpi file regularly, either drag and drop it into a window, or from about:addons -> install addon from file. You don't need an installer 🙂

**Comment by minch-dev** [comment]
Updated the readme to include this info

**Comment by southern-boy** [comment]
I did not see any XPI file when I extract the master.  I also see no
releases directory when looking at it on github.

Thank you.

**Comment by minch-dev** [comment]
I marked the Releases section with a red rectangle:
![image](https://github.com/minch-dev/DownTheMoon/assets/65311549/f012dbae-87c3-4a8e-90d4-a7d02421ccd9)
You can also acces releases using a url https://github.com/minch-dev/DownTheMoon/releases

**Comment by minch-dev** [comment]
Fxd!
